### ISSUE TITLE
[Bug] APC and APCU mismatch

### ISSUE THREAD

**Issue by OwenMelbz** [prismicio-community/php-kit#162]
Hi,

There seems to be a mismatch in the code with apc and apcu.

The Apc driver specifically uses apcu e.g.

```php
public function has($key)
{
    return \apcu_exists($key);
}
```

however the "default cache" method checks for the wrong extension e.g.

```php
if (extension_loaded('apc') && ini_get('apc.enabled')) {
    return new ApcCache();
}
```

`extension_loaded('apc')` returns `false`.

This is because it's registered as `apcu`

Changing the code to `extension_loaded('apcu')` fixes the problem and enables the built in cache.

--

Can we look into getting this patched and released?

Thanks :)

**Comment by c0nst4ntin** [comment]
@OwenMelbz I'm happy to tell you, that this issue was finally fixed in **[feat!: support PHP 8 #190](https://github.com/prismicio-community/php-kit/pull/190)**

To make use of this change please upgrade to **[Version 5.2.0](https://github.com/prismicio-community/php-kit/releases/tag/5.2.0)**

Sadly, I couldn't use your old PR, since the branch got deleted. I will proceed to close this issue. 

If you run into any trouble with the package again, please feel free to open up a new Issue
